import { createContext, useState, useContext } from 'react';
import { uz, ru, enUS } from 'date-fns/locale';

const locales = {
  uz: uz,
  ru: ru,
  en: enUS
};

const translations = {
  uz: {
    // Sidebar
    dashboard: "Boshqaruv paneli",
    resumes: "Rezyumalar",
    jobs: "Ish o'rinlari",
    analytics: "Analitika",
    activities: "Faoliyat loglari",
    adminPanel: "Admin Panel",

    // Dashboard cards
    resumesTitle: "Rezyumalar",
    jobsTitle: "Ish o'rinlari",
    applicantsTitle: "Moslikllar",
    totalApplied: "Talablar qilindi",
    viewDetails: "Ko'rish",

    // Table headers
    rank: "RANK",
    candidate: "NOMZOD",
    avgScore: "O'RTACHA BALL",
    topScore: "ENG YUQORI BALL",
    appliedJobs: "TAHILLLAR SONI",
    actions: "AMALLAR",

    // Sections
    topCandidates: "Eng yaxshi nomzodlar reytingi",
    recentAnalysis: "Oxirgi tahlillar",
    candidateName: "NOMZOD",
    jobPosition: "ISH O'RNI",
    matchLevel: "MOSLIK DARAJASI",
    date: "SANA",

    // Job positions
    qituvchi: "O'qituvchi",

    // Top button
    top10: "Top 10",

    // Resumes page
    resumesPage: "Rezyumalar",
    uploadResume: "Rezyume yuklash",
    dragDropText: "PDF faylni bu yerga sudrab tashlang yoki",
    clickToUpload: "yuklash uchun bosing",
    supportedFormats: "Qo'llab-quvvatlanadigan format: PDF (maksimal 10MB)",
    fileName: "FAYL NOMI",
    uploadDate: "YUKLANGAN SANA",
    fileSize: "HAJMI",
    status: "HOLATI",
    analyzed: "Tahlil qilindi",
    pending: "Kutilmoqda",
    view: "Ko'rish",
    delete: "O'chirish",
    analyze: "Tahlil qilish",
    compareWithJobs: "Ish o'rinlari bilan solishtirish",
    searchResumes: "Rezyumalarni qidirish...",
    noResumes: "Hozircha rezyumalar yo'q",
    uploadFirst: "Birinchi rezyumeni yuklang",
    totalResumes: "Jami rezyumalar",
    analyzedResumes: "Tahlil qilingan",
    pendingResumes: "Kutilmoqda",
    resumeBuilder: "Resume yaratish",

    // Jobs page
    jobsPage: "Ish o'rinlari",
    addNewJob: "Yangi vakansiya qo'shish",
    jobTitle: "Vakansiya nomi",
    jobTitlePlaceholder: "Masalan: Senior Python Developer",
    company: "Kompaniya",
    companyPlaceholder: "Kompaniya nomi",
    location: "Joylashuv",
    locationPlaceholder: "Masalan: Toshkent, O'zbekiston",
    salary: "Maosh",
    salaryPlaceholder: "Masalan: 3000-5000 USD",
    employmentType: "Ish turi",
    fullTime: "To'liq vaqt",
    partTime: "Qisman vaqt",
    contract: "Shartnoma",
    internship: "Amaliyot",
    requirements: "Talablar",
    requirementsPlaceholder: "Har bir talabni yangi qatordan yozing...",
    description: "Tavsif",
    descriptionPlaceholder: "Vakansiya haqida batafsil...",
    postedDate: "E'lon qilingan",
    applicants: "Nomzodlar",
    matchRate: "Moslik darajasi",
    activeJobs: "Faol vakansiyalar",
    totalApplicants: "Jami nomzodlar",
    avgMatchRate: "O'rtacha moslik",
    edit: "Tahrirlash",
    close: "Yopish",
    save: "Saqlash",
    cancel: "Bekor qilish",
    noJobs: "Hozircha vakansiyalar yo'q",
    addFirstJob: "Birinchi vakansiyani qo'shing",
    searchJobs: "Vakansiyalarni qidirish...",
    viewApplicants: "Nomzodlarni ko'rish",

    // Analytics page
    analyticsPage: "Analitika",
    resumesTrend: "Rezyumalar dinamikasi",
    jobsTrend: "Vakansiyalar dinamikasi",
    topSkills: "Eng talab qilinadigan ko'nikmalar",
    matchStatistics: "Moslik statistikasi",
    monthlyAnalysis: "Oylik tahlil",
    skillName: "Ko'nikma",
    demand: "Talab",
    averageMatch: "O'rtacha moslik",
    totalUploaded: "Yuklangan",
    totalPosted: "E'lon qilingan",
    successRate: "Muvaffaqiyat darajasi",
    january: "Yanvar",
    february: "Fevral",
    march: "Mart",
    april: "Aprel",
    may: "May",
    june: "Iyun",
    july: "Iyul",
    august: "Avgust",
    september: "Sentabr",
    october: "Oktabr",
    november: "Noyabr",
    december: "Dekabr",
    excellent: "Zo'r",
    good: "Yaxshi",
    average: "O'rtacha",
    poor: "Past",

    // Activity Logs page
    activityLogsPage: "Faoliyat loglari",
    allActivities: "Barcha faoliyatlar",
    todayActivities: "Bugungi faoliyatlar",
    recentActivities: "So'nggi faoliyatlar",
    activityType: "Faoliyat turi",
    user: "Foydalanuvchi",
    time: "Vaqt",
    details: "Tafsilotlar",
    all: "Hammasi",
    uploads: "Yuklashlar",
    analyses: "Tahlillar",
    jobPosts: "Vakansiyalar",
    filterByType: "Tur bo'yicha filter",
    searchLogs: "Loglarni qidirish...",
    resumeUploaded: "Rezyume yuklandi",
    resumeAnalyzed: "Rezyume tahlil qilindi",
    jobPosted: "Vakansiya e'lon qilindi",
    jobUpdated: "Vakansiya yangilandi",
    jobDeleted: "Vakansiya o'chirildi",
    matchFound: "Moslik topildi",
    ago: "oldin",
    minute: "daqiqa",
    minutes: "daqiqa",
    hour: "soat",
    hours: "soat",
    day: "kun",
    days: "kun",
    justNow: "Hozirgina",

    // Admin Panel page
    adminPanelPage: "Admin Panel",
    systemSettings: "Tizim sozlamalari",
    userManagement: "Foydalanuvchilar",
    databaseStats: "Database statistikasi",
    systemStatus: "Tizim holati",
    backupExport: "Backup va Export",
    aiSettings: "AI sozlamalari",
    matchingThreshold: "Moslik chegarasi",
    activeUsers: "Faol foydalanuvchilar",
    totalUsers: "Jami foydalanuvchilar",
    serverStatus: "Server holati",
    diskSpace: "Disk maydoni",
    cpuUsage: "CPU yuklanish",
    memoryUsage: "Xotira yuklanish",
    online: "Faol",
    offline: "Faol emas",
    healthy: "Yaxshi",
    warning: "Ogohlantirish",
    critical: "Kritik",
    lastBackup: "Oxirgi backup",
    createBackup: "Backup yaratish",
    exportData: "Ma'lumotlarni eksport qilish",
    exportResumes: "Rezyumalarni eksport",
    exportJobs: "Vakansiyalarni eksport",
    exportAll: "Hammasini eksport",
    exportApplicants: "Nomzodlarni eksport",
    aiModel: "AI Model",
    modelVersion: "Model versiyasi",
    accuracy: "Aniqlik",
    updateModel: "Modelni yangilash",
    userName: "Foydalanuvchi",
    email: "Email",
    role: "Rol",
    admin: "Admin",
    hr: "HR Manager",
    lastActive: "Oxirgi faollik",
    addUser: "Foydalanuvchi qo'shish",
    systemHealth: "Tizim salomatligi",
    matches: "Mosliklar",
    languageChanged: "Til {lang} ga o'zgartirildi",
    notifications: "Bildirishnomalar",
    recentMessages: "So'nggi xabarlar",
    markAllRead: "Barchasini oqish",
    noMessages: "Xabarlar yo'q",
    menu: "Menu",
    account: "Account",
    profileSettings: "Profil Sozlamalari",
    logout: "Chiqish",
    allNotificationsRead: "Barcha bildirishnomalar o'qildi",
    warehouse: "Ombori",
    resumesDesc: "Barcha rezyumalarni boshqarish va tahlil qilish",
    resumesLoadError: "Rezyumalarni yuklashda xatolik yuz berdi",
    resumeUploadSuccess: "Rezyume muvaffaqiyatli yuklandi",
    resumeUploadError: "Rezyumeni yuklashda xatolik yuz berdi",
    invalidFileType: "Faqat PDF fayllari ruxsat etilgan",
    confirmDelete: "Haqiqatanham o'chirmoqchimisiz?",
    deleteSuccess: "Muvaffaqiyatli o'chirildi",
    deleteError: "O'chirishda xatolik yuz berdi",
    analysisStarted: "Tahlil boshlandi",
    analysisError: "Tahlilda xatolik yuz berdi",
    analysisResults: "Tahlil natijalari",
    skills: "Ko'nikmalar",
    experience: "Tajriba",
    education: "Ma'lumot",
    showing: "Ko'rsatilmoqda",
    of: "dan",
    myJobs: "Mening vakansiyalarim",
    findJobs: "Vakansiyalar izlash",
    submitApplication: "Ariza topshirish",
    jobApplications: "Vakansiyaga arizalar",
    jobSeeker: "Ish qidiruvchi",
    seekerDesc: "Ish izlayman",
    employer: "Ish beruvchi",
    employerDesc: "Xodim izlayman",
    selectRole: "Ro'lingizni tanlang",
    companyName: "Kompaniya nomi"
  },

  ru: {
    dashboard: "Панель управления",
    resumes: "Резюме",
    jobs: "Вакансии",
    analytics: "Аналитика",
    activities: "Логи активности",
    adminPanel: "Админ Панель",
    resumesTitle: "Резюме",
    jobsTitle: "Вакансии",
    applicantsTitle: "Соответствия",
    totalApplied: "Всего заявок",
    viewDetails: "Просмотр",
    rank: "РАНГ",
    candidate: "КАНДИДАТ",
    avgScore: "СРЕДНИЙ БАЛЛ",
    topScore: "МАКС БАЛЛ",
    appliedJobs: "КОЛ-ВО ЗАЯВОК",
    actions: "ДЕЙСТВИЯ",
    topCandidates: "Рейтинг лучших кандидатов",
    myApplications: "Мои заявки",
    myResume: "Мое резюме",
    aiInterview: "AI собеседование",
    applicants: "Кандидаты",
    recentAnalysis: "Последние анализы",
    candidateName: "КАНДИДАТ",
    jobPosition: "ДОЛЖНОСТЬ",
    matchLevel: "УРОВЕНЬ СООТВЕТСТВИЯ",
    date: "ДАТА",
    qituvchi: "Учитель",
    top10: "Топ 10",
    resumesPage: "Резюме",
    uploadResume: "Загрузить резюме",
    dragDropText: "Перетащите PDF файл сюда или",
    clickToUpload: "нажмите для загрузки",
    supportedFormats: "Поддерживаемый формат: PDF (максимум 10MB)",
    fileName: "ИМЯ ФАЙЛА",
    uploadDate: "ДАТА ЗАГРУЗКИ",
    fileSize: "РАЗМЕР",
    status: "СТАТУС",
    analyzed: "Проанализировано",
    pending: "Ожидание",
    view: "Просмотр",
    delete: "Удалить",
    analyze: "Анализировать",
    compareWithJobs: "Сравнить с вакансиями",
    searchResumes: "Поиск резюме...",
    noResumes: "Пока нет резюме",
    uploadFirst: "Загрузите первое резюме",
    totalResumes: "Всего резюме",
    analyzedResumes: "Проанализировано",
    pendingResumes: "Ожидание",
    resumeBuilder: "Создать резюме",
    jobsPage: "Вакансии",
    addNewJob: "Добавить вакансию",
    jobTitle: "Название вакансии",
    jobTitlePlaceholder: "Например: Senior Python Developer",
    company: "Компания",
    companyPlaceholder: "Название компании",
    location: "Местоположение",
    locationPlaceholder: "Например: Ташкент, Узбекистан",
    salary: "Зарплата",
    salaryPlaceholder: "Например: 3000-5000 USD",
    employmentType: "Тип занятости",
    fullTime: "Полная занятость",
    partTime: "Частичная занятость",
    contract: "Контракт",
    internship: "Стажировка",
    requirements: "Требования",
    requirementsPlaceholder: "Каждое требование с новой строки...",
    description: "Описание",
    descriptionPlaceholder: "Подробное описание вакансии...",
    postedDate: "Дата публикации",
    matchRate: "Уровень соответствия",
    activeJobs: "Активные вакансии",
    totalApplicants: "Всего кандидатов",
    avgMatchRate: "Средний уровень",
    edit: "Редактировать",
    save: "Сохранить",
    cancel: "Отмена",
    noJobs: "Пока нет вакансий",
    addFirstJob: "Добавьте первую вакансию",
    searchJobs: "Поиск вакансий...",
    viewApplicants: "Показать кандидатов",
    analyticsPage: "Аналитика",
    resumesTrend: "Динамика резюме",
    jobsTrend: "Динамика вакансий",
    topSkills: "Самые востребованные навыки",
    matchStatistics: "Статистика соответствия",
    monthlyAnalysis: "Месячный анализ",
    skillName: "Навык",
    demand: "Спрос",
    averageMatch: "Средний уровень",
    totalUploaded: "Загружено",
    totalPosted: "Опубликовано",
    successRate: "Успешность",
    january: "Январь",
    february: "Февраль",
    march: "Март",
    april: "Апрель",
    may: "Май",
    june: "Июнь",
    july: "Июль",
    august: "Август",
    september: "Сентябрь",
    october: "Октябрь",
    november: "Ноябрь",
    december: "Декабрь",
    excellent: "Отлично",
    good: "Хорошо",
    average: "Средне",
    poor: "Низко",
    activityLogsPage: "Логи активности",
    allActivities: "Все активности",
    todayActivities: "Сегодняшние активности",
    recentActivities: "Последние активности",
    activityType: "Тип активности",
    user: "Пользователь",
    time: "Время",
    details: "Детали",
    all: "Все",
    uploads: "Загрузки",
    analyses: "Анализы",
    jobPosts: "Вакансии",
    filterByType: "Фильтр по типу",
    searchLogs: "Поиск логов...",
    resumeUploaded: "Резюме загружено",
    resumeAnalyzed: "Резюме проанализировано",
    jobPosted: "Вакансия опубликована",
    jobUpdated: "Вакансия обновлена",
    jobDeleted: "Вакансия удалена",
    matchFound: "Найдено соответствие",
    ago: "назад",
    minute: "минута",
    minutes: "минут",
    hour: "час",
    hours: "часов",
    day: "день",
    days: "дней",
    justNow: "Только что",
    adminPanelPage: "Админ Панель",
    systemSettings: "Системные настройки",
    userManagement: "Пользователи",
    databaseStats: "Статистика БД",
    systemStatus: "Статус системы",
    backupExport: "Backup и Export",
    aiSettings: "Настройки AI",
    matchingThreshold: "Порог соответствия",
    activeUsers: "Активные пользователи",
    totalUsers: "Всего пользователей",
    serverStatus: "Статус сервера",
    diskSpace: "Дисковое пространство",
    cpuUsage: "Использование CPU",
    memoryUsage: "Использование памяти",
    online: "Онлайн",
    offline: "Офлайн",
    healthy: "Хорошо",
    warning: "Предупреждение",
    critical: "Критично",
    lastBackup: "Последний backup",
    createBackup: "Создать backup",
    exportData: "Экспорт данных",
    exportResumes: "Экспорт резюме",
    exportJobs: "Экспорт вакансий",
    exportAll: "Экспорт всего",
    exportApplicants: "Экспорт кандидатов",
    aiModel: "AI Модель",
    modelVersion: "Версия модели",
    accuracy: "Точность",
    updateModel: "Обновить модель",
    userName: "Пользователь",
    email: "Email",
    role: "Роль",
    admin: "Админ",
    hr: "HR Менеджер",
    lastActive: "Последняя активность",
    addUser: "Добавить пользователя",
    systemHealth: "Здоровье системы",
    matches: "Соответствия",
    languageChanged: "Язык изменён на {lang}",
    notifications: "Уведомления",
    recentMessages: "Последние сообщения",
    markAllRead: "Прочитать все",
    noMessages: "Нет сообщений",
    close: "Закрыть",
    menu: "Меню",
    account: "Аккаунт",
    profileSettings: "Настройки профиля",
    logout: "Выход",
    allNotificationsRead: "Все уведомления прочитаны",
    warehouse: "Хранилище",
    resumesDesc: "Управление и анализ всех резюме",
    resumesLoadError: "Ошибка при загрузке резюме",
    resumeUploadSuccess: "Резюме успешно загружено",
    resumeUploadError: "Ошибка при загрузке резюме",
    invalidFileType: "Разрешены только PDF файлы",
    confirmDelete: "Вы уверены, что хотите удалить?",
    deleteSuccess: "Успешно удалено",
    deleteError: "Ошибка при удалении",
    analysisStarted: "Анализ начат",
    analysisError: "Ошибка при анализе",
    analysisResults: "Результаты анализа",
    skills: "Навыки",
    experience: "Опыт",
    education: "Образование",
    showing: "Показано",
    of: "из",
    myJobs: "Мои вакансии",
    findJobs: "Поиск вакансий",
    submitApplication: "Отправить заявку",
    jobApplications: "Заявки на вакансию",
    jobSeeker: "Соискатель",
    seekerDesc: "Ищу работу",
    employer: "Работодатель",
    employerDesc: "Ищу сотрудников",
    selectRole: "Выберите роль",
    companyName: "Название компании"
  },

  en: {
    dashboard: "Dashboard",
    resumes: "Resumes",
    jobs: "Job Positions",
    analytics: "Analytics",
    activities: "Activity Logs",
    adminPanel: "Admin Panel",
    resumesTitle: "Resumes",
    jobsTitle: "Job Positions",
    applicantsTitle: "Matches",
    totalApplied: "Total Applied",
    viewDetails: "View Details",
    rank: "RANK",
    candidate: "CANDIDATE",
    avgScore: "AVG SCORE",
    topScore: "TOP SCORE",
    appliedJobs: "APPLIED JOBS",
    actions: "ACTIONS",
    topCandidates: "Top Candidates Rating",
    recentAnalysis: "Recent Analysis",
    candidateName: "CANDIDATE",
    jobPosition: "JOB POSITION",
    matchLevel: "MATCH LEVEL",
    date: "DATE",
    qituvchi: "Teacher",
    top10: "Top 10",
    resumesPage: "Resumes",
    uploadResume: "Upload Resume",
    dragDropText: "Drag & drop PDF file here or",
    clickToUpload: "click to upload",
    supportedFormats: "Supported format: PDF (max 10MB)",
    fileName: "FILE NAME",
    uploadDate: "UPLOAD DATE",
    fileSize: "SIZE",
    status: "STATUS",
    analyzed: "Analyzed",
    pending: "Pending",
    view: "View",
    delete: "Delete",
    analyze: "Analyze",
    compareWithJobs: "Compare with Jobs",
    searchResumes: "Search resumes...",
    noResumes: "No resumes yet",
    uploadFirst: "Upload your first resume",
    totalResumes: "Total Resumes",
    analyzedResumes: "Analyzed",
    pendingResumes: "Pending",
    resumeBuilder: "Create Resume",
    jobsPage: "Job Positions",
    addNewJob: "Add New Job",
    jobTitle: "Job Title",
    jobTitlePlaceholder: "e.g., Senior Python Developer",
    company: "Company",
    companyPlaceholder: "Company name",
    location: "Location",
    locationPlaceholder: "e.g., Tashkent, Uzbekistan",
    salary: "Salary",
    salaryPlaceholder: "e.g., 3000-5000 USD",
    employmentType: "Employment Type",
    fullTime: "Full-time",
    partTime: "Part-time",
    contract: "Contract",
    internship: "Internship",
    requirements: "Requirements",
    requirementsPlaceholder: "Each requirement on a new line...",
    description: "Description",
    descriptionPlaceholder: "Detailed job description...",
    postedDate: "Posted Date",
    applicants: "Applicants",
    matchRate: "Match Rate",
    activeJobs: "Active Jobs",
    totalApplicants: "Total Applicants",
    avgMatchRate: "Avg Match Rate",
    edit: "Edit",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    noJobs: "No jobs yet",
    addFirstJob: "Add your first job",
    searchJobs: "Search jobs...",
    viewApplicants: "View Applicants",
    analyticsPage: "Analytics",
    resumesTrend: "Resumes Trend",
    jobsTrend: "Jobs Trend",
    topSkills: "Top Required Skills",
    matchStatistics: "Match Statistics",
    monthlyAnalysis: "Monthly Analysis",
    skillName: "Skill",
    demand: "Demand",
    averageMatch: "Average Match",
    totalUploaded: "Uploaded",
    totalPosted: "Posted",
    successRate: "Success Rate",
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",
    excellent: "Excellent",
    good: "Good",
    average: "Average",
    poor: "Poor",
    activityLogsPage: "Activity Logs",
    allActivities: "All Activities",
    todayActivities: "Today's Activities",
    recentActivities: "Recent Activities",
    activityType: "Activity Type",
    user: "User",
    time: "Time",
    details: "Details",
    all: "All",
    uploads: "Uploads",
    analyses: "Analyses",
    jobPosts: "Job Posts",
    filterByType: "Filter by Type",
    searchLogs: "Search logs...",
    resumeUploaded: "Resume uploaded",
    resumeAnalyzed: "Resume analyzed",
    jobPosted: "Job posted",
    jobUpdated: "Job updated",
    jobDeleted: "Job deleted",
    matchFound: "Match found",
    ago: "ago",
    minute: "minute",
    minutes: "minutes",
    hour: "hour",
    hours: "hours",
    day: "day",
    days: "days",
    justNow: "Just now",
    adminPanelPage: "Admin Panel",
    systemSettings: "System Settings",
    userManagement: "User Management",
    databaseStats: "Database Statistics",
    systemStatus: "System Status",
    backupExport: "Backup & Export",
    aiSettings: "AI Settings",
    matchingThreshold: "Matching Threshold",
    activeUsers: "Active Users",
    totalUsers: "Total Users",
    serverStatus: "Server Status",
    diskSpace: "Disk Space",
    cpuUsage: "CPU Usage",
    memoryUsage: "Memory Usage",
    online: "Online",
    offline: "Offline",
    healthy: "Healthy",
    warning: "Warning",
    critical: "Critical",
    lastBackup: "Last Backup",
    createBackup: "Create Backup",
    exportData: "Export Data",
    exportResumes: "Export Resumes",
    exportJobs: "Export Jobs",
    exportAll: "Export All",
    exportApplicants: "Export Applicants",
    aiModel: "AI Model",
    modelVersion: "Model Version",
    accuracy: "Accuracy",
    updateModel: "Update Model",
    userName: "User Name",
    email: "Email",
    role: "Role",
    admin: "Admin",
    hr: "HR Manager",
    lastActive: "Last Active",
    addUser: "Add User",
    systemHealth: "System Health",
    matches: "Matches",
    languageChanged: "Language changed to {lang}",
    notifications: "Notifications",
    recentMessages: "Recent Messages",
    markAllRead: "Mark all read",
    noMessages: "No messages",
    menu: "Menu",
    account: "Account",
    profileSettings: "Profile Settings",
    logout: "Logout",
    allNotificationsRead: "All notifications read",
    warehouse: "Warehouse",
    resumesDesc: "Manage and analyze all resumes",
    resumesLoadError: "Error loading resumes",
    resumeUploadSuccess: "Resume uploaded successfully",
    resumeUploadError: "Error uploading resume",
    invalidFileType: "Only PDF files are allowed",
    confirmDelete: "Are you sure you want to delete?",
    deleteSuccess: "Successfully deleted",
    deleteError: "Error deleting",
    analysisStarted: "Analysis started",
    analysisError: "Error during analysis",
    analysisResults: "Analysis Results",
    skills: "Skills",
    experience: "Experience",
    education: "Education",
    showing: "Showing",
    of: "of",
    myJobs: "My Jobs",
    findJobs: "Find Jobs",
    submitApplication: "Submit Application",
    jobApplications: "Job Applications",
    jobSeeker: "Job Seeker",
    seekerDesc: "Looking for a job",
    employer: "Employer",
    employerDesc: "Looking for employees",
    selectRole: "Select your role",
    companyName: "Company Name"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'uz';
  });

  const handleSetLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    const langTranslations = translations[language] || translations['uz'];
    return langTranslations[key] || key;
  };

  const currentLocale = locales[language] || locales.uz;

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, locale: currentLocale }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const getLocale = (lang) => {
  return locales[lang] || locales.uz;
};